services:
  web:
    container_name: example-service
    build: .
    ports:
      - "3000:8080"
    environment:
      - PORT=8080
      - HOSTNAME=0.0.0.0
    env_file:
      - 'env/key-metrics.env'
      - 'env/pg.env'
  database:
    image: postgres:latest
    env_file:
      - 'env/pg.env'

